name: Sync Dev to Main

on:
  push:
    branches: ["dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write  # Ensure the workflow can write to the repository

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Copy dev files to main/dev folder
        run: |
          mkdir -p main/dev
          rsync -av --exclude='main' . main/dev/
          rm -rf main/dev/.git main/dev/.github

      - name: Commit and push to main
        working-directory: main
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add dev/
          git commit -m "Sync dev branch to main/dev folder" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
